name: pokedex_search
description: Package to introduce all 151 pokemons of the first generation.
version: 1.0.2
homepage: https://github.com/LucssCarvalho/pokedex_search

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: